# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: 
  - linux
  - osx

language: R
sudo: false
cache: packages

# only run for pushes to master branch
branches:
  only:
   - master
   
  
r_packages:
  - covr

cache:
  packages: yes


before_install:
  - Rscript -e 'if(!"INLA" %in% rownames(installed.packages())) { install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE) }'
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
   
